console.log("[PenguinAddons] Loading config")
import "./utils/config";
console.log("[PenguinAddons] Loading commands");
import "./utils/commands";
console.log("[PenguinAddons] Loading worldLoad");
import "./utils/worldLoad";
console.log("[PenguinAddons] Loading LobbySwap");
import "./features/LobbySwap";
console.log("[PenguinAddons] Loading BalStatus");
import "./features/BalStatus";
console.log("[PenguinAddons] Loading BalTimer");
import "./features/BalTimer";
console.log("[PenguinAddons] Loading ChestHighlight");
import "./features/ChestHighlight";
console.log("[PenguinAddons] Loading PowderMining");
import "./features/PowderMining";
console.log("[PenguinAddons] Loading AntiSpleef");
import "./features/AntiSpleef";
console.log("[PenguinAddons] Loaded!");
ChatLib.chat("&b[&cPenguin&6Addons&b]&r Loaded!");