import PogObject from "../../PogData";

const values = new PogObject("BalAddons", {
    version: "0.0.2",
    balStatus: null,
    balFound: null,
    balSpawning1_5Lock: null,
    balSpawnPosX: null,
    balSpawnPosY: null,
    balSpawnPosZ: null,
    balSpawnDist: null,
    balWidth: null,
    balHealth: null,
    balAlivePosX: null,
    balAlivePosY: null,
    balAlivePosZ: null,
    area: null,
    inCH: null,
    tempswap: null,
    balSpawnOverlayToggle: false,
    bal75OverlayToggle: false,
    bal50OverlayToggle: false,
    bal33OverlayToggle: false,
    balDeathOverlayToggle: false,
    balStatusOverlayToggle: false,
    balSpawningTimerWorldToggle: false,
    balSpawningTimerTick: null,
    balSpawningTimerSecond: null,
    balDeadTimerWorldToggle:false,
    balDeadTimerTick: null,
    balDeadTimerSecond: null,
    balSpawningHUDToggle: false,
    balAliveHUDToggle: false,
    balDeadHUDToggle: false,
});

export default values;